### ISSUE TITLE
Safe string

### ISSUE THREAD

**Issue by copy** [sgreben/ocaml-redis-protocol#2]
The current version mixes uses of `bytes` and `string`, however it is not compiled with `-safe-string`, so the types are the same and compilation fails when `-safe-string` is added. It seems that no mutation is used, so changing all uses of `bytes` to `string` (plus the corresponding uses) should work, but it'd be a breaking change.

**Comment by sgreben** [comment]
Fixed by @copy and @bramford in #4 / #6. Many thanks for the fixes!
